site_name: Bq computacional (FCUL)
nav:
- Prefácio: 'index.md'
- Instalação (software e dados): data_software.md
- 1 - A linguagem Python:
  - Conceitos básicos: 'basics.md'
  - Exercícios (série 1): 'exercises_1.md'
  - Coleções e iterações: 'collections_iterations.md'  
  - Listas e dicionários: 'more_on_lists_dicts.md'
  - Strings: 'strings.md'
  - Funções e módulos: 'funcs_modules.md'
  - Exercícios de treino: 'problems.md'
  - Ficheiros de texto: 'files.md'
- 2 - Textos estruturados:
  - Exemplo 1 (UniProt txt): 'uniprot_txt.md'
- 3 - Módulos científicos:
  - numpy: sm_numpy_scipy.md
  - Exemplo, curva titulação: sm_ph.md
  - Exercícios de treino 2: 'problems2.md'
  - pandas: sm_pandas.md
  - Exemplo, regressão linear: sm_linreg.md
  - sympy: sm_sympy.md
  - Algoritmos numéricos: sm_algorithms.md
use_directory_urls: false
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
theme:
  name: 'material'
  language: 'pt'
  palette:
    primary: 'blue'
    accent: 'Deep orange'
extra_css:
  - 'stylesheets/extra.css'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  #- pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde