# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Programação em Python
author: António Ferreira
copyright: "2022"
logo: newlogo.png

only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: prog_bqcomp.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
  launch_buttons: false

sphinx:
  config:
    language: "pt_PT"
    nb_merge_streams: true

parse:
  myst_enable_extensions:
    # - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    #- substitution
    #- strikethrough
    #- tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context
